### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by federicoiosue**

### CODE REVIEW

**Comment by F43nd1r** [comment]
Thank you for your contribution.
There are a few things left untranslated:
 - `best guess, you may need to adjust this`
 - `Acrarium is developed by <a href=...>F43nd1r</a>. <a href=...>Code</a> is licensed under <a href=...E>Apache License v2</a>. Logo by <a href=...>Mirza Zulfan</a>.`

Could you take a look at these as well?
 
 Also please do not translate the license header.

**Comment by federicoiosue** [comment]
Done!

**Comment by F43nd1r** [comment]
Nice! I went ahead and tried to compare it to the english source. Looks like your file is a lot shorter - thus missing quite a few keys. Did you by chance start from an old version?

**Comment by federicoiosue** [comment]
My fault, maybe I trunked the file. I've added the missing ones.

**Pull request merged**
